name: Build & Push Docker Image
on:
  push:
    branches: [main, whitelabel, dreamcrew]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: |
            ghcr.io/msbnw/social-publisher:latest
            ghcr.io/msbnw/social-publisher:${{ github.sha }}
            registry.fly.io/dreamcrew-social-publisher:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
